services:
  - type: web
    name: video-splitter-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: false
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PORT
        value: "5000"
      - key: FLASK_DEBUG
        value: "false"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: video-splitter-disk
      mountPath: /tmp
      sizeGB: 10
    healthCheckPath: /health
    preDeployCommand: ""
    postDeployCommand: ""